installdir = $(pkgdatadir)/skin_default/ratings

dist_install_DATA = \
	AUS-AV.png \
	AUS-C.png \
	AUS-E.png \
	AUS-G.png \
	AUS-M.png \
	AUS-MA.png \
	AUS-na.png \
	AUS-P.png \
	AUS-PG.png \
	AUS-R.png \
	AUS-X.png \
	blank.png \
	ETSI-4.png \
	ETSI-5.png \
	ETSI-6.png \
	ETSI-7.png \
	ETSI-8.png \
	ETSI-9.png \
	ETSI-10.png \
	ETSI-11.png \
	ETSI-12.png \
	ETSI-13.png \
	ETSI-14.png \
	ETSI-15.png \
	ETSI-16.png \
	ETSI-17.png \
	ETSI-18.png \
	ETSI-ALL.png \
	ETSI-BC.png \
	ETSI-na.png
