installdir = $(pkglibdir)/python/Components/Renderer

install_PYTHON = \
	__init__.py \
	AnalogClockLCD.py \
	AudioIcon.py \
	Bhclock.py \
	Canvas.py \
	ChannelNumber.py \
	CiModuleControl.py \
	Cover.py \
	DRRunningText.py \
	EtAnalogClockLCD.py \
	FixedLabel.py \
	FrontpanelLed.py \
	GaugeRender.py \
	Label.py \
	LcdPicon.py \
	Listbox.py \
	NextEpgInfo.py \
	NextEvents.py \
	PicCript.py \
	PicEmu2.py \
	Picon.py Pig.py \
	Pixmap.py \
	PositionGauge.py \
	Progress.py \
	RatingIconLabel.py \
	Renderer.py \
	RollerCharLCD.py \
	RollerCharLCDLong.py \
	RunningText.py \
	VideoSize.py \
	VolumeText.py \
	VRunningText.py \
	VWatches.py
