name: enigma2

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        gcc: [15]
        python: ['3.14']
    env:
      CC: "gcc-${{ matrix.gcc }}"
      CXX: "g++-${{ matrix.gcc }}"
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: install python packages and flake8
      run: |
        pip3 install netifaces pyopenssl python-wifi service_identity twisted flake8
    - name: install dev packages
      run: |
        sudo apt-get -q update
        sudo apt install docbook-xsl gettext automake build-essential libcrypt-dev libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libfribidi-dev libtool libavahi-client-dev libgif-dev mm-common libfreetype6-dev libjpeg-turbo8-dev libcurl4-openssl-dev python3-dev zlib1g-dev swig libssl-dev linux-libc-dev libwebp-dev --reinstall docbook-xsl
    - name: Check format PEP8
      run: |
        echo "checking locale format..."
        find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
        echo "checking PEP8 validation..."
        flake8 --builtins="_,ngettext,pgettext" --ignore=W191,W503,W504,E128,E501,E722,F841,F824 . --exit-zero
        echo "check format PEP8 completed!"
# PEP8 :- IGNORE CODES
# W191 : indentation contains tabs
# W503 : line break before binary operator
# W504 : line break after binary operator
# E128 : continuation line under-indented for visual indent
# E501 : line too long (> 79 characters)
# E722 : do not use bare 'except'
    - name: Build enigma2 dependencies, gcc-${{ matrix.gcc }}
      env:
        CC: "gcc-${{ matrix.gcc }}"
        CXX: "g++-${{ matrix.gcc }}"
      run: |
        echo "installing libdvbsi++"
        pushd .
        cd /tmp
        git clone --depth 1 https://github.com/oe-alliance/libdvbsi.git
        cd libdvbsi
        autoreconf -i
        ./configure
        make
        sudo make install
        popd
        echo "installing libsigc++-3"
        pushd .
        cd /tmp
        git clone --depth 1 https://github.com/dbus-cxx/libsigc--3.0.git
        cd libsigc--3.0
        autoreconf -i
        ./configure
        make
        sudo make install
        popd
        echo "installing tuxbox"
        pushd .
        cd /tmp
        git clone --depth 1 https://github.com/OpenPLi/tuxtxt.git
        cd tuxtxt/libtuxtxt
        autoreconf -i
        ./configure --with-boxtype=generic DVB_API_VERSION=5
        make
        sudo make install
        cd ../tuxtxt
        autoreconf -i
        ./configure --with-boxtype=generic DVB_API_VERSION=5
        make
        sudo make install
        popd


    - name: build enigma2
      env:
        CC: "gcc-${{ matrix.gcc }}"
        CXX: "g++-${{ matrix.gcc }}"
      run: |
        echo "compiling enigma2"
        autoreconf -i
        ./configure --with-libsdl=no --with-boxtype=nobox --enable-dependency-tracking ac_cv_prog_c_openmp=-fopenmp --with-gstversion=1.0 --with-textlcd
        make
        python -m compileall .
        echo "checking enigma2 compiles completed"
